name: mizan
description: Mizan - حسابداری و انبارداری محلی
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^0.13.6
  path_provider: ^2.0.14
  path: ^1.8.3
  file_picker: ^5.2.5
  sqflite: ^2.2.7
  sqflite_common_ffi: ^2.3.6
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  crypto: ^3.0.2
  intl: ^0.18.0
  shamsi_date: ^1.1.0
  image: ^4.0.17

  # تولید PDF و نمایش/پرینت
  pdf: ^3.10.4
  printing: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets کلی (تصاویر، فونتها و غیره)
  assets:
    - assets/
    - assets/fonts/

  # ثبت فونت برای اپ (برای نمایش داخل اپ و Theme)
  fonts:
    - family: IRANSansXFaNum
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANSansWeb_Light.ttf
          weight: 300